[pytest]

python_functions    = test_*
python_classes      = Test*
python_files        = test_*
testpaths           = tests

markers             =
    base: all tests related to polaris.base submodules
    base_handler: all tests related to polaris.base.base_handler submodules
