[pytest]

python_functions    = test_*
python_classes      = Test*
python_files        = test_*
testpaths           = tests

markers             =
    base:           all tests related to polaris.base submodules
    handler:        all tests related to the BaseHandler class and its implemenatations
    linter:         all tests related to the Linter class and Lint function implementations
    example:        all tests related to the polaris.example linter implementation
